//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Persona
{
	public virtual object Nombre
	{
		get;
		set;
	}

	public virtual object Apellido
	{
		get;
		set;
	}

	public virtual object DNI
	{
		get;
		set;
	}

	public virtual object Tipo
	{
		get;
		set;
	}

}

